root = "."
tmp_dir = "tmp"

[build]
  # bin = "./tmp/main"
  # The next one from above is how your application will be started after compiled.
  full_bin = "./tmp/main -zap-devel"
  cmd = "go build -o ./tmp/main ."
  delay = 5000
  exclude_dir = ["assets", "tmp", "vendor","hack"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true
[color]
  app = "chat-controller"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
