apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: chat-operator
build:
  artifacts:
  - image: controller
    custom:
      buildCommand: |
        CGO_ENABLED=0 go build -o _output/manager main.go
        DOCKER_BUILDKIT=1 docker build --tag=$IMAGE --build-arg BUILD_ENV=builder-binary .
      dependencies:
        dockerfile:
          path: Dockerfile
          buildArgs:
            BUILD_ENV: builder-binary
deploy:
  kustomize:
    paths:
    - config/crd
    - config/default