apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: chat-operator
build:
  artifacts:
  - image: quay.io/hown3d/chat-operator
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - config/crd
    - config/default