# permissions for end users to view rockets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocket-viewer-role
rules:
- apiGroups:
  - chat.accso.de
  resources:
  - rockets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chat.accso.de
  resources:
  - rockets/status
  verbs:
  - get
