/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hown3d/chat-operator/api/chat.accso.de/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRockets implements RocketInterface
type FakeRockets struct {
	Fake *FakeChatV1alpha1
	ns   string
}

var rocketsResource = schema.GroupVersionResource{Group: "chat.accso.de", Version: "v1alpha1", Resource: "rockets"}

var rocketsKind = schema.GroupVersionKind{Group: "chat.accso.de", Version: "v1alpha1", Kind: "Rocket"}

// Get takes name of the rocket, and returns the corresponding rocket object, and an error if there is any.
func (c *FakeRockets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Rocket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rocketsResource, c.ns, name), &v1alpha1.Rocket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rocket), err
}

// List takes label and field selectors, and returns the list of Rockets that match those selectors.
func (c *FakeRockets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RocketList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rocketsResource, rocketsKind, c.ns, opts), &v1alpha1.RocketList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RocketList{ListMeta: obj.(*v1alpha1.RocketList).ListMeta}
	for _, item := range obj.(*v1alpha1.RocketList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rockets.
func (c *FakeRockets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rocketsResource, c.ns, opts))

}

// Create takes the representation of a rocket and creates it.  Returns the server's representation of the rocket, and an error, if there is any.
func (c *FakeRockets) Create(ctx context.Context, rocket *v1alpha1.Rocket, opts v1.CreateOptions) (result *v1alpha1.Rocket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rocketsResource, c.ns, rocket), &v1alpha1.Rocket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rocket), err
}

// Update takes the representation of a rocket and updates it. Returns the server's representation of the rocket, and an error, if there is any.
func (c *FakeRockets) Update(ctx context.Context, rocket *v1alpha1.Rocket, opts v1.UpdateOptions) (result *v1alpha1.Rocket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rocketsResource, c.ns, rocket), &v1alpha1.Rocket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rocket), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRockets) UpdateStatus(ctx context.Context, rocket *v1alpha1.Rocket, opts v1.UpdateOptions) (*v1alpha1.Rocket, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rocketsResource, "status", c.ns, rocket), &v1alpha1.Rocket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rocket), err
}

// Delete takes name of the rocket and deletes it. Returns an error if one occurs.
func (c *FakeRockets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rocketsResource, c.ns, name), &v1alpha1.Rocket{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRockets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rocketsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RocketList{})
	return err
}

// Patch applies the patch and returns the patched rocket.
func (c *FakeRockets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Rocket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rocketsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Rocket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rocket), err
}
