apiVersion: chat.accso.de/v1alpha1
kind: Rocket
metadata:
  name: rocket-sample-single
  namespace: default
spec:
  version: "4.0"
  adminSpec: 
    username: "test"
    email: "test@test"
---

apiVersion: chat.accso.de/v1alpha1
kind: Rocket
metadata:
 name: rocket-sample-no-versions
 namespace: default
spec:
  adminSpec: 
    username: "test"
    email: "test@test"

---

apiVersion: chat.accso.de/v1alpha1
kind: Rocket
metadata:
 name: rocket-sample-high-aval
 namespace: default
spec:
  adminSpec:
    username: "test-abc"
    email: "test@mail.com"
  replicas: 3
  version: "3.18"
  database:
    replicas: 3

